### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by DRSDavidSoft** [sjinks/knex-mariadb#1]
Hi there, I'm using this package like this:
```javascript
		const database = { ... };
		const knex = require('knex')({
			client: require('knex-mariadb'),
			connection: {
				host: database.server,
				port: database.port,
				user: database.username,
				password: database.password,
				database: database.name,
				charset: 'utf8'
			}
		});
```

But I get the following message:
```
C:\Users\David\Workspace\Project\node_modules\knex-mariadb\index.js:4
  driverName = 'mariadb';
             ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\Users\David\Workspace\Project\src\app\index.js:34:12
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Am I missing anything?

---

Also:

```bash
$ node --version
v10.16.3
```

**Comment by ghost** [comment]
See #2 .  This is only a one-file module and a very simple drop-in replacement for `mysql2`; just copy and paste my `index.js` into your project, instead of pulling it in from npm or github.

What I like about this is not only the performance increase, but the fact that `mariadb` is an official package.  This is superior to sequelize because of it's simplicity.  Ping @rusher

**Comment by jbyington** [comment]
This will fix the syntax error

```
const Client_MySQL = require('knex/lib/dialects/mysql/index');

class Client_MariaDB extends Client_MySQL {
	
  constructor(...args) {
	super(...args);
	this.driverName = 'mariadb';
  }

  _driver () {
    return require('mariadb/callback');
  }

  validateConnection (connection) {
    return connection.isValid();
  }
};

module.exports = Client_MariaDB;
```
